[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@prb/math/=lib/prb-math/src/',
    "@pyth/contracts/=lib/pyth-sdk-solidity/",
]
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[invariant]
runs = 1000
fail_on_revert = true


solc_version = "0.8.23"
